const fs = require('fs');
const replace = require('replace');

const data = [
	'key',
	'r/viHfrthMvlepAj1LfUPgiRYNSo17HhByHoAIZ4D0s=',
	'location',
	'/',
	'split',
	'pathname',
	'-',
	'length',
	'media-player',
	'/ajax/v4_movie_episodes/',
	'GET',
	'json',
	'html',
	'.pa-server',
	'ajax',
	'100%',
	'500px',
	'#f3f378',
	'Helvetica',
	'raised',
	'#c91c54',
	'white',
	'black',
	'setup',
	'setupError',
	'on',
	'ready',
	'mobileChecker',
	'<div id="overlay-yesplugin-main" style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%;"></div>',
	'prepend',
	'#media-player',
	'complete',
	'#episodes-sv-',
	' .ep-item',
	'click',
	' .ep-item[data-index=',
	']',
	'play',
	'levels',
	'getQualityLevels',
	'label',
	'Auto',
	'setCurrentQuality',
	'seek',
	'offset',
	'setItem',
	'firstFrame',
	'getItem',
	'pause',
	'text',
	'#time-resume',
	'show',
	'modal',
	'#pop-resume',
	'time',
	'adTime',
	'getPosition',
	'start',
	'addTag',
	'end',
	'removeTag',
	'error',
	'load',
	'indexOf',
	'push',
	'data-id',
	'attr',
	'each',
	'.server-item.vip',
	'#sv-',
	'.server-item',
	'sv-loaded',
	'addClass',
	'.server-item.embed',
	'data-index',
	'#ep-',
	'setSeconds',
	'getHours',
	'getMinutes',
	'getSeconds',
	'0',
	':',
	'hide',
	'#yes-resume',
	'#no-resume',
	'stop',
	'/ajax/movie_token?eid=',
	'&mid=',
	'/ajax/movie_sources/',
	'?x=',
	'&y=',
	'embed',
	'WEBRTC_SUPPORT',
	'#content-embed',
	'#embed-loading',
	'src',
	'#iframe-embed',
	'',
	'playlist',
	'getScript',
	'/ajax/movie_embed/',
	'active',
	'removeClass',
	'.server-list-item',
	'trim',
	'.playing-on',
	'.sv-loaded',
	'protocol',
	'//',
	'hostname',
	'/movie/',
	'/watching.html',
	'pushState',
	'auto_next',
	'player_settings',
	'stringify',
	'cookie',
	'.bp-btn-auto',
	'.ep-item',
	'data-server',
	'hasClass',
	'parse',
	'href',
	'.html'
];

for (let i = data.length - 1; i >= 0; i--) {
	replace({
		regex: new RegExp('_0x36e2.' + i + '.', 'gi'),
		replacement: '\'' + data[i] + '\'',
		paths: ['./src/dummy.txt'],
		recursive: true,
		silent: true
	});
}
